POSTGRESQL_USERNAME: postgres
POSTGRESQL_PASSWORD: sris0799
POSTGRESQL_HOST: localhost
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: securedocument

ACTIVE_PROFILE: dev

EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: saggarwal1999@gmail.com
EMAIL_PASSWORD: djun ahsr cwln ctlp
VERIFY_EMAIL_HOST: http://localhost:8080
